# {dotfiles}/bombadil.toml

# Path to your dotfiles relative to your $HOME directory
dotfiles_dir = "dotfiles"

[settings]
# An array of toml files paths containing the variables to inject in your templatized dotfiles
# You can have multiple var files as long as variable names does not colide.
# vars = [ "vars.toml" ]

# An array of post install shell commands
posthooks = [ "nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'" ]

[settings.dots]
hyprland = { source = "hypr", target = ".config/hypr" }
alacritty = { source = "alacritty", target = ".config/alacritty" }
zsh = { source = ".zsh", target = ".zsh" }
btop = { source = "btop", target = ".config/btop" }
cava = { source = "cava", target = ".config/cava" }
dunst = { source = "dunst", target = ".config/dunst" }
eww = { source = "eww", target = ".config/eww" }
gxrfetch = { source = "gxrfetch", target = ".config/gxrfetch" }
kitty = { source = "kitty", target = ".config/kitty" }
ncmpcpp = { source = "ncmpcpp", target = ".config/ncmpcpp" }
nvim = { source = "nvim", target = ".config/nvim" }
waybar = { source = "waybar", target = ".config/waybar" }
wofi = { source = "wofi", target = ".config/wofi" }
zshrc = { source = ".zshrc", target = ".zshrc" }
